### ISSUE TITLE
Cobbler fails silently if unable to open log file

### ISSUE THREAD

**Issue by alanoe** [cobbler/cobbler#1319]
I spent some time today because my logging in views.py was not being done due to wrong permissions in /var/log/cobbler/cobbler.log (iirc views.py is run by apache user). This happens because Cobbler logger initialization ignores exceptions when opening the log file. Code block:

```
    try:
        self.logfile = open(logfile, "a")
    except IOError:
        # You likely don't have write access, this logger will just print
        # things to stdout.
        pass
```

imho Cobbler should not fail silently here. If there is no write access to the log file, probably something is wrong.

**Comment by SchoolGuy** [comment]
Although we are using now the Python 3 standard library logger this should be checked against.

**Comment by watologo1** [comment]
I also have been there.
This works now by this:
# Temporary hack, a clean solution seems to be tricky.
# Defining a variable in our Apache startup code seem not to work, it is still set later when this code is executed via
# Cobbler.

# This is necessary to prevent apache to try to access the file
LOG_FILE = "/var/log/cobbler/cobbler.log"
try:
    if not os.path.isfile(LOG_FILE):
        open(LOG_FILE, 'a').close()
    if os.access(LOG_FILE, os.W_OK):
        logging.config.fileConfig('/etc/cobbler/logging_config.conf')
except Exception:
    pass

012bca33af7e0a8f544ee6f4b80ae15176c82590
7dafc770b2bf2b035701d66e6083f2f009675e04
It's dirty, because the --log-file=NAME param is now ignored and similar.

But this issue can be closed IMO. The remaining issue(s) are different and not that critical anymore.
-> closing.
