### ISSUE TITLE
Create a migration script to Cobbler 3.0

### ISSUE THREAD

**Issue by alanoe** [cobbler/cobbler#1349]
There have been several filesystem restructurings/renamings recently. Create a migration script to make migration from latest Cobbler version to 3.0 easier.

**Comment by SchoolGuy** [comment]
Okay so I changed after 3.0.0 the format of the settings file. Since most distros do not replace the settings file with the one from upstream we need a migration script which can be executed to upgrade to 3.0.1 and apply the new scheme.

We have also to adjust the release notes to match it with the github releases where stuff is currently documented.

**Comment by SchoolGuy** [comment]
Okay so the migration script was done with https://github.com/cobbler/cobbler/pull/2154 but the release notes were not adjusted...

**Comment by SchoolGuy** [comment]
Blog-Entry for migration was done: [https://cobbler.github.io/blog/2019/10/24/cobbler_3.0.1_migration.html](https://cobbler.github.io/blog/2019/10/24/cobbler_3.0.1_migration.html)

**Comment by SchoolGuy** [comment]
This can be closed now

**Comment by opoplawski** [comment]
I somehow missed that the storage locations for the json files changed from /var/lib/cobbler/config/{distros,profiles,systems,etc..}.d to /var/lib/cobbler/collections/{distros,profiles,systems,etc...}.  This means on upgrade all the configuration is lost.  I see no mention of this anywhere, and I don't see a script to help with this.

**Comment by SchoolGuy** [comment]
@opoplawski You mean an Upgrade form 2.8.x to 3.x.x?

**Comment by opoplawski** [comment]
Yes

**Comment by opoplawski** [comment]
See #2291 for an initial start.

**Comment by watologo1** [comment]
I like it.
Beside next_server, we'd like to introduce filename to be overridden via system parameter.
This would also be a new param. Theoretically this script must be maintained on a per version base...?
What I found and what might help is from uyuni project:
https://github.com/uyuni-project/uyuni/blob/master/susemanager/bin/migrate-cobbler.sh
This one does not transfer the data itself, but may help to find all data that changed directories, due to cleanups...
