### ISSUE TITLE
create unittests for core cobbler functionality

### ISSUE THREAD

**Issue by jmaas** [cobbler/cobbler#1492]

**Comment by alanoe** [comment]
imho we should define what to implement before starting to do it. imho first step is to improve and complete the CLI/XML-RPC integration tests I started last year. Some features are harder to test because they require a more complex environment to run on. 

I'd like to know more about this Travis CI you have set up, is there any documentation about it somewhere? Do we have shell access to the test server?

**Comment by SchoolGuy** [comment]
So update on this: We are currently roughly at about 25% coverage and are using Github CI, since Travis changed their pricing model. I will consider this closed when we have over 50% coverage with unit tests instead of our integration tests. This means that we have a lot of work to do but it will be worth it in my eyes.

**Comment by SchoolGuy** [comment]
I superseede this issue with #2625
