### ISSUE TITLE
port cobbler to a lightweight web framework

### ISSUE THREAD

**Issue by jmaas** [cobbler/cobbler#1493]
reuse standard components
add ability to add a rest api more easily

**Comment by jmaas** [comment]
i've started work on a port to CherryPy.
i can send a PR in a few days so we can discuss it.

**Comment by alanoe** [comment]
I do not see the benefit of changing the server-side web framework. I successfully use Django in most projects I work on. I'd like to understand the motivation of this change better. Some points below:

- RESTful API vs higher level XML-RPC interface. REST API has its benefits but the recent trend of using it for all HTTP interfaces is overrated imho. Main advantages of REST API over higher-level XML-RPC API are (1) reuse HTTP implementations of caching, throttling and versioning, (2) possibility of using more compact JSON format instead of XML in HTTP request/response body (and thus increase performance) and (3) it is supported natively by all programming languages (eg Javascript requires external library to use XML-RPC). imho none of these benefits are essential to Cobbler. XML-RPC has the benefit of simpler development and use by a Python client, so imho that's good reason enough to keep it. We could evaluate changing to JSON-RPC if we think XML-RPC is a bottleneck somewhere, but afaik it is not. Also, I dont see how changing to a lighter web framework would help in a REST API, it is very easy to create a REST API in Django.

- Reuse standard components. Do you mean reuse custom components or use standard HTML components? We already do the latter. If you mean the former, what custom components are we missing? Maybe you meant an UI improvement in general? I dont see how changing the server-side web framework will help any of those issues.

Are there are other benefits of changing from Django to a lighter web framework?

**Comment by jmaas** [comment]
Hi Alan,

I'm only suggesting this for cobblerd, also i want to provide a REST api next to the current xmlrpc one, using a webframework makes this more easy. We also would gain the ability to move easily to a mvc architecture.

Using Django for the webclient is all good.

**Comment by alanoe** [comment]
Jorgen, Django is a web framework and can be easily used to build a REST API. Also, MVC architecture can be implemented using any web framework and Django stimulates it because it already splits UI code in views and controllers (templates and views, respectively, in Django terminology). Even for the cobbler daemon, I see no benefit in changing the web framework. Pls tell me if I am missing something.

**Comment by FlorianneRaven** [comment]
First having a real documentation of the api ?
i need to talk to cobbler via php...

**Comment by SchoolGuy** [comment]
So this issue is now obsolete. This is due to the introduction of the new WebUI that will utilize the XML-RPC API and the removal of the Django-based UI.
