### ISSUE TITLE
Latest release is not a parent of master more recently than 2014

### ISSUE THREAD

**Issue by autocracy** [cobbler/cobbler#1675]
The first common version between master and v2.6.11 (the latest release tag) is 1b5dbc3 from April 2014.

Requesting a merge into master, possibly via `git checkout master && git merge v2.6.11 --strategy=ours`

**Comment by jmaas** [comment]
Can you explain why we'd want to do that?

**Comment by autocracy** [comment]
I guess I'm in a state where perhaps I don't understand the release / development flow.

I spent some time debugging an issue with a repository using https in 2.6.11 and found notable changes between that release and master.

Then general pattern I was expected with release branches is along the lines of finding a fix for 2.6 series merged into master rather than what looks like a very long string of cherry picks. There's also the 2.8 series branch that I may understand even less given it isn't released but the merge-base for that is back in 2015.

Perhaps the step here for me is instead to ask what the release theory is for Cobbler since I don't understand this repository pattern.

**Comment by nacc** [comment]
AFAIK, master is a moving development branch. Fixes for various releases get cherry-picked down to the appropriate release branch. 'release28' may exist because a 2.8.1 is being planned (although not cut yet).

**Comment by jmaas** [comment]
master = development, current master is a major refactoring and cleanup, so it has diverged a lot from the release branches. this is also where major new features should go 

release26 is the current release branch, only bugfixes and small feature improvements are committed. occasionally new releases are cut

release28 is not yet released, and initially was not planned for. but due to some feature removals from master this release branch will be used to deprecated these features.

yes, we're kind off in a mess... i like to get 2.8.0 released soon, but real-life has gotten in the way (again). so we need some time to document the deprecations and get 2.8.0 out. the 2.8 branch will be something like a LTS branch so that users that rely on current features will be supported for years too come, or find alternatives for the dropped features.

hope this clarifies that state of current cobbler "development"
