### ISSUE TITLE
SUSE version detection is broken

### ISSUE THREAD

**Issue by brejoc** [cobbler/cobbler#1963]
I'm talking about this part of the code: https://github.com/cobbler/cobbler/blob/master/cobbler/utils.py#L974-L982

There are three problems. Leap and SLES 15 are no longer using `/etc/SuSE-release` and don't even ship it. Also the version detection is only working for openSUSE and not even for Tumbleweed. The patch-level for SLES is just discarded and e.g. for SLES12 SP3 we get `('suse', 12.0)`.

This ties into the question I've already asked [here](https://github.com/cobbler/cobbler/pull/1961#issuecomment-451186313): Wouldn't it make more sense to differentiate between SLES and openSUSE? I think it would make sense.

Returns could look like this:

* openSUSE Tumbleweed => `('opensuse tumbleweed', '20181224')`
* openSUSE Leap 15.0 => `('opensuse leap', 15.0)`
* SLES 15.0 => `('sles', 15.0)`

**Comment by brejoc** [comment]
@jmaas What do you think about this proposal? Of course then we should use that nomenclature in all the different places.

**Comment by jmaas** [comment]
I do agree that differentiation makes more sense.

But, the "breed" concept is used allover the place (pxegen, buildiso) and allready causes bugs due to differences in kopts between sles and opensuse (i know one regarding cdrom booting).

So if we differentiate the distros in the current codebase it will become more polluted with if/then/else comparisons increasing the maintenance burden.

Ultimately i'd like the breed concept to go away, the most flexible user and maintainer friendly solution i see is to include distro specific options (eg. kopts) in the distro_signatures.json file. But it will be a major undertaking....

Going forward on futurize i'd suggest to get things working asap  for your targets and we'll take it from there.

Does this make sense?

**Comment by jmaas** [comment]
Fixed in futurize branch.
