### ISSUE TITLE
cobbler, cobbler-web missing in EPEL 8 repository

### ISSUE THREAD

**Issue by zabel47** [cobbler/cobbler#2157]
i am missing the cobbler, cobbler-web rpm's  in the fedora epel/8/ repository.
the packages are available in:
https://dl.fedoraproject.org/pub/epel/7/x86_64/Packages/c/
but not in:
https://dl.fedoraproject.org/pub/epel/8/Everything/x86_64/Packages/c/

when will these packages be available for EPEL 8 version?

**Comment by SchoolGuy** [comment]
I have tried to look up who maintains the package there but I wasn't able to find someone. I will have a look asap and get back here.

**Comment by opoplawski** [comment]
This is going to be tricky.  koan 2.0.7.1 is provided as a module built from the cobbler spec, so EPEL is currently blocking branching cobbler.  I suspect this is going to need to wait until we can build modules in EPEL8 which is currently target for around the time of RHEL8.1.

**Comment by opoplawski** [comment]
I've created https://copr.fedorainfracloud.org/coprs/orion/cobbler/ for testing purposes at least.

However, complicating matters even more, it seems that if the rhn-tools module (which provides koan from the cobbler spec) is enabled, then cobbler is excluded from all dnf transactions.  So you'll need to:
```
dnf module disable rhn-tools
```
if it is enabled before you can install cobbler.  This probably isn't a big deal since not much there is useful for someone using cobbler I think.  I'll probably need to build koan in the cobbler copr though.

**Comment by opoplawski** [comment]
FWIW - I've added koan as well.

**Comment by SchoolGuy** [comment]
@zabel47 Can we close this from your point? Or is there still work to be done?

**Comment by opoplawski** [comment]
I'm closing this here as this is an EPEL request, not an upstream request.
