### ISSUE TITLE
Document Terraform provider

### ISSUE THREAD

**Issue by SchoolGuy** [cobbler/cobbler#2166]
Apparently we have a Terraform provider: https://www.terraform.io/docs/providers/cobbler/index.html

This needs to be docuemented and we need guides on how to use it.

**Comment by hbokh** [comment]
FYI The current Terraform Cobbler Provider is **not compatible** with Cobbler 3 due to changes in the XMLRPC API.
I've forked both `cobblerclient` and `terraform-provider-cobbler` to make the right calls, but as of today it does not have all the commands included.

Repos:
- https://github.com/wearespindle/cobblerclient
- https://github.com/wearespindle/terraform-provider-cobbler

I can help on documenting, since I've done so already at $WORK.

**Comment by SchoolGuy** [comment]
I would appreciate that a lot. I personally would just document a few easy and a more complex example and let the rest of the docs be on their side. @hbokh

**Comment by hbokh** [comment]
Solved with Document Terraform provider #2528
