### ISSUE TITLE
SELinux issue when service is restarted

### ISSUE THREAD

**Issue by kwizart** [cobbler/cobbler#2183]
This issue was initially reported at
https://bugzilla.redhat.com/show_bug.cgi?id=1754430

There is a SELinux denial when the cobblerd service is restarted because of the permissions of the web.ss and others webui_sessions files.

I'm not sure to understand if this is 3.0.x only or also only exists in 2.8.x, but for me there is a need to understand why cobblerd (uid root) tries to read theses files...
Of course it can probably be fixed by using 640 perm on theses files. (to be tested) but it just workaround the problem.

**Comment by SchoolGuy** [comment]
@kwizart If you look at the code then you will see that this is required by everything which accesses cobbler. It is an authentication file that make access possible. I see that this is a problem for you but on short term I don't see an options to make this problem go away...

The code where this is generated is in `cobbler/cobblerd.py +43` and onwards.

**Comment by SchoolGuy** [comment]
This is by the way also a problem for 2.8.x

**Comment by SchoolGuy** [comment]
Other points where you have context for this file is:

- `cobbler/cli.py + 335`
- `cobbler/utils.py +1825`

**Comment by SchoolGuy** [comment]
So due to the fact that Cobbler need to run as root currently and the Apache 2 user needs access to both files this won't be fixed by us. At least not until we have cleaned up everything very very good. Thus closing this and leaving the selinux policy mess to downstream. I recommend running this without selinux anyway because of the many permissions we need currently.
