### ISSUE TITLE
cobbler import fails with AttributeError

### ISSUE THREAD

**Issue by bowlerct** [cobbler/cobbler#2194]
Tag v3.0.1

Running cobbler import fails with message
```
DEBUG | shell triggers finished successfully
INFO | Exception occured: <class 'AttributeError'>
INFO | Exceptin value: 'NoneType' object has no attribute 'get_import_manager'
....
```

The endof the stack trace is
```
 File "../lib/python3.6/site-packages/cobbler/api.py" line 861, in import_tree
   import_module = self.get_module_by_name("manage_import_signatures").get_import_manager(sef._collection_mgr, logger)
```

**Comment by bowlerct** [comment]
Modifying file cobbler/api.py to change "manage_import_signatures" to "manager.import_signatures" got me further but then more errors occurred.

```
INFO | creating new distro: CentOS7.6-Server-x86_64
INFO | Exception occured: <class UnbooundLocalError>
INFO | Exception value: local variable 'distro' referenced before assignment
...
```
The stack trace referenced the module manager.import_signature

Inspecting the file import_signature.py I found that there were two local variables in the method "add_entry" which are masking imports: distro and profile.

Renaming the local variables to "new_distro" and "new_profile" solved my issue and I can now import successfully. There were 16 references to the local variable "distro" and 8 references to "profile" that I changed.

**Comment by SchoolGuy** [comment]
@bowlerct Would you mind sharing your patch? Maybe even as a PR?

**Comment by watologo1** [comment]
I expect this one is fixed already by this:
commit d0e731edeba70dc749bca53139de2c02b9f8fad3
Author: Richard <richard.berger@temple.edu>
Date:   Thu Oct 17 02:28:58 2019 -0400

    Fixes various issues found during cobbler import

-        import_module = self.get_module_by_name("manage_import_signatures").get_import_manager(self._collection_mgr, logger)
+        import_module = self.get_module_by_name("managers.import_signatures").get_import_manager(self._collection_mgr, logger)


Please try latest HEAD code base or patch this one in.
I already close this one, as one can see the old code, broken code line using:

manage_import_signatures

instead of:

managers.import_signatures
