### ISSUE TITLE
`cobbler system powerstatus` fails with 'no power type set for system'

### ISSUE THREAD

**Issue by xenlo** [cobbler/cobbler#2230]
### Describe the bug
The power status management is looking for command starting with `fence_` in `/usr/sbin/` or `/sbin/`.

This fails with cobbler running on RedHat with `ipmitool` as Power Management Type as the command is located `/usr/bin/ipmitool`.

### To Reproduce

1. Install cobbler on a RedHat based distro
2. Create a system in cobbler with `--power-type=ipmilan`
```
cobbler system edit --name=foo --power-type=ipmilan --power-address=foo-mgmt.example.org --power-user=Administrator --power-pass=PASSWORD
```
3. Run a system powerstatus on that system
```
cobbler system powerstatus --name=declinesim
```
```
Exception value: 'no power type set for system'
```

### Expected behavior

Cobbler code should find the command in the `$PATH` and not in a list of hard-coded locations.

### Workaround
You can create a soft link to the command where cobbler is looking like this:
```
ln -s /usr/bin/ipmitool /usr/sbin/fence_ipmitool
```

### Version
- 2.8.5
- But should affect v3

### Screenshots

```
[root@cherrysim ~]# ll /usr/sbin/ipmitool*
lrwxrwxrwx. 1 root root 17 Jan  7 09:14 /usr/sbin/ipmitool -> /usr/bin/ipmitool
[root@cherrysim ~]# cobbler system powerstatus --name=declinesim
task started: 2020-01-07_091443_power
task started (id=Power management (status), time=Tue Jan  7 09:14:43 2020)
Exception occured: <class 'cobbler.cexceptions.CX'>
Exception value: 'no power type set for system'
Exception Info:
  File "/usr/lib/python2.7/site-packages/cobbler/utils.py", line 106, in die
    raise CX(msg)

failed to execute power task on declinesim
*** TASK COMPLETE ***
```

### Additional context

This bug as been escaladed by @shahzebsiddiqui  on gitter. He was running on cobbler2.8.5 but looking through the code it also affect the cobbler in version 3 as path is also hardcoded [in code here](https://github.com/cobbler/cobbler/blob/master/cobbler/power_manager.py#L54).

**Comment by watologo1** [comment]
Some background:

It looks like there was an fence_ipmitool in the fence-agents project long time ago.
cobbler commit f158fa7b9017f8326ba7c65475cac7d8ad658f37
reverted therefore the fence_ipmitool template.

ipmilan fence-agent which uses ipmitool below has been advised to be used and pass power_id=1 to make use of the lanplus (ipmi 2.0 protocol) which in the end certainly is exactly the same as the ipmitool fence agent was.
How this still worked (ipmitool as default type, but not avail, I am not sure. SUSE at least shipped for quite a while with a fence_ipmitool script which may have been the one dropped by fence-agents project, due to code duplication (assumption)).

Anyway... The fence_ipmitool command which is propagated in cobbler to be the default is exactly the same as fence_ipmilan -P

From man fence_ipmilan:
       -P, --lanplus
              Use Lanplus to improve security of connection (Default Value: 0)
In fact security does not  matter. It's about the old version 1.5 vs 2.0 ipmi protocol standard.
Nowadays nearly all IPMIs work with version 2.0 exclusively.

IMO 2 things should be done here:
- Create a hard link from /usr/sbin/fence_ipmilan to fence_ipmitool
In fact we already do this in the latest SUSE .spec in the install section:
ln -s fence_ipmilan %{buildroot}/%{_sbindir}/fence_ipmitool
- Send a patch to fence-agents project to:
  Change default on fence_ipmilan to use lanplus by default

Alternatively or additionally on longterm (also depending on fence_agents project response), ipmitool could get replace by ipmilan default power type. But this needs long time of deprecation as it is a long existing --power-type option used by other tools.

PS: 
ln -s /usr/bin/ipmitool /usr/sbin/fence_ipmitool
would not work, ipmitool is not a fence_agent, it must be:
ln -s fence_ipmilan %{buildroot}/%{_sbindir}/fence_ipmitool

**Comment by watologo1** [comment]
Ideally, instead of the hardlink:
ln -s fence_ipmilan %{buildroot}/%{_sbindir}/fence_ipmitool
an alias is used:
alias fence_ipmitool="fence_ipmilan -P"
but this would be a very distribution and shell specific solution...

I at least opened:
https://github.com/ClusterLabs/fence-agents/issues/314

**Comment by SchoolGuy** [comment]
This would be ideally fixed with having a setting where you can either set a path for the binary of the power option or setting the directory where the `fence_agent`'s are located. If they are not found we should not fall back to something but rather then immediately show an error.
