### ISSUE TITLE
How to create rpm package for Centos?

### ISSUE THREAD

**Issue by 4gemenot** [cobbler/cobbler#2250]
### Version

````paste below
````
Cobbler version 3.1.1

### Question

How to create rpm package for Centos?

**Comment by hbokh** [comment]
Use `rpmbuild`: `rpmbuild -vv -bb cobbler.spec`.
Here's a tutorial [rpmbuild tutorial - how to build rpm packages](https://rogerwelin.github.io/rpm/rpmbuild/2015/04/04/rpmbuild-tutorial-part-1.html).
But in the end the created package won't install due to dependencies on `python36-cheetah`, which is a non-existing package.

See https://github.com/cobbler/cobbler/issues/2238#issuecomment-575765258

**Comment by SchoolGuy** [comment]
Or you could use the rpms built via the Dockerfile. Alternatively you could do as @hbokh suggested. @4gemenot

**Comment by 4gemenot** [comment]
Thank you Gents.
