### ISSUE TITLE
Cannot create new management class

### ISSUE THREAD

**Issue by opoplawski** [cobbler/cobbler#2288]
### Describe the bug

Trying to save new management class in gui I get:

Remote exception: class name must be a string

### Version

3.1.1

### Additional context

```
  File "/usr/lib/python3.8/site-packages/cobbler/remote.py", line 2245, in _dispatch
    return method_handle(*params)

  File "/usr/lib/python3.8/site-packages/cobbler/remote.py", line 896, in modify_item
    method(arg)

  File "/usr/lib/python3.8/site-packages/cobbler/items/mgmtclass.py", line 97, in set_class_name
    raise CX(_("class name must be a string"))
```

**Comment by aaron-baidu** [comment]
This is because mgmtclass.py is importing:

from past.builtins import str

and the code 
        if not isinstance(name, str):
            raise CX(_("class name must be a string"))

type(name) here evaluates to 
<class 'str'>
but isinstance(name, str) is using past.builtins.str, which evaluates to 
<class 'str'> == <class 'past.types.oldstr.oldstr'>
which is always false.

My solution was dumb but works for me so far. 
I changed the opening line;

from past.builtins import str as oldstr

It is likely that past.builtins is trying to handle some encoded strings put into cobbler files from past versions of cobbler (ie python2) - for which case it's likely you need two 'if' checks (for str and past.builtins.str) - but likely upstream of this code you should just convert all past.types.oldstr.oldstr to str types if they come up. The import line I wrote above allows us to compare arguments passed with oldstr and str if we want - I haven't coded that comparison, just 'set aside' the oldstr type for now while leaving the import. Perhaps with a #todo above it.
