### ISSUE TITLE
how Disable the variable replace

### ISSUE THREAD

**Issue by A-BenMao** [cobbler/cobbler#2306]
### Version

````paste below
2.8.5
````

### Question

if the template file like kickstart file have $variabler ,the $variabler must be defined ,but ,in some times, i cat not difined the variabler .because the variabler in script like this:
````
%include /tmp/include

%pre --interpreter=/bin/bash
disk=$(awk 'BEGIN{min = 20444785640; low = 104857600} {if ($3+0 < min+0 && $3+0 > low+0 && $4 ~ /^s..$/) { min = $3; disk = $4 } } END{print disk}' /proc/partitions)
cat > /tmp/include << EOF
bootloader --location=mbr --driveorder=$disk --append="nomodeset crashkernel=auto rhgb quiet inter_idle.max_cstate=0 processor.max_cstate=0"
ignoredisk --only-use=$disk
EOF
%end
````

please help me how Disable the variable replace?
thanks

**Comment by SchoolGuy** [comment]
Well you cannot disable the templating itself. But a template is just a file where the information get's replaced. So since you have a bash script you could assign these cobbler/cheetah variables to bash and then you can check with bash if the variable has a content or not.

As an alternative you can have a look at https://cheetahtemplate.org/users_guide/index.html
There is explained how you write templates for cobbler.

**Comment by A-BenMao** [comment]
thanks ,i used a bash script ,then used wget this script and run in the kickstart like this:

%pre --interpreter=/bin/bash
wget http://$http_server/post/select-disk.sh
chmod +x select-disk.sh
bash select-disk.sh
%end
