### ISSUE TITLE
Cobbler default url and login/password

### ISSUE THREAD

**Issue by jehutyy** [cobbler/cobbler#2307]
I'm trying to leverage the cobbler terraform provider to provision my cobbler instance. 
I guess that the provider uses cobbler's api to send actions and thus needs to access a running instance.
I have been browsing cobbler documentation in order to find default login/password as well as default url it appears that it is not that clear. 

I installed cobbler and cobbler_web which I understand is necessary to access cobbler via http.

1 / Is cobbler_web package needed to access cobbler api ? 
2 / cobbler package exposes http://localhost/cobbler_api via apache. Is this the right url to use ?
2' / cobbler_web package exposes http://localhost/cobbler_web. Is this the right url to use ? 
3 / what purpose does cobbler_web package serve ? 
4 / Last but not least, what are default login password to access whatever api is exposed by cobbler ? I see a default_password_crypted in /etc/cobbler/settings but neither login directive nor url.

**Comment by SchoolGuy** [comment]
1. Yes it is needed.
2. Yes that is the right URL if you are on the system where cobbler is installed. Otherwise replace localhost with the ip of the system.
3. It contains the static files used to render the web frontend. Meaning more specific the Django application which is the web frontend.
4. If you have a default cobbler the login is `cobbler` and `cobbler`. This is found here: https://cobbler.readthedocs.io/en/latest/user-guide/web-interface.html#web-interface

**Comment by SchoolGuy** [comment]
This was documented and thus can be closed.
