### ISSUE TITLE
Netboot is not being disabled after pxe boot

### ISSUE THREAD

**Issue by paulrattu** [cobbler/cobbler#2321]
### Version

````paste below
Cobbler 2.8.5
````
### Question

After building a machine successfully and the machine reboots, Netboot isn't being disabled in cobbler so the machine will just pxe boot again. I can see the kickstart_done snippet is being called(even thought it looks like everything is commented out inside the snippet). What do I need to do in order for this to happen?

**Comment by SchoolGuy** [comment]
You can disable it manually with: `cobbler system edit --name systemname --netboot-enabled 0`

**Comment by paulrattu** [comment]
That's what I've been doing up until now(or manually disabling netboot in the cobbler web-gui). The issue is I want Cobbler to automatically turn off netboot after a machine is finished building.

**Comment by watologo1** [comment]
This very much depends on your distro.
This patch might give you an idea:

commit df9854b2e18342b0bec1fd4627370205454c1162
    Fix install loop for SUSE via info=http://%s/cblr/svc/op/nopxe/system/%s param

For SUSE the process to disable PXE (by invoking REST cobbler api):
http://%s/cblr/svc/op/nopxe/system/%s

Changed from an autoyast script to a boot parameter info=http://...
This also covers non-autoyast installations.

Whatever distro you install, you should be able to look up what is going wrong now?

**Comment by hbokh** [comment]
> (even thought it looks like everything is commented out inside the snippet). 

That is because it is a Cheetah template, not a "regular script".
See https://cheetahtemplate.org/index.html

The `kickstart_done` should call the `pxe_just_once`, based on the "breed" aka distro.
Ref.: https://github.com/cobbler/cobbler/blob/release28/snippets/kickstart_done#L14-L29
When successful the webserver access log will show a line with `nopxe`, e.g.

`192.168.1.1 - - [18/Apr/2020:10:47:51 +0200] "GET /cblr/svc/op/nopxe/system/linux004 HTTP/1.1" 200 4 "-" "Wget/1.18 (linux-gnu)"`

**Comment by paulrattu** [comment]
Yup, that was it hbokh. I didn't realize there was on option for that in the cobbler settings. Turned that setting to 1 and it started working. Next time I'll look closer at the config.

Thanks
