### ISSUE TITLE
[VOTE] The future of Cobbler Web

### ISSUE THREAD

**Issue by SchoolGuy** [cobbler/cobbler#2342]
### Is your feature request related to a problem?

The current web-frontend is old and clumsy, not complete and basing on an EOL Django version.

### The behavior you'd like

Get rid of the old look, have a feature or near feature complete web-interface and get rid of that EOL Django Version.

### Alternatives you've considered

If we don't go for Django, I would very much appreciate if the web frontend will be split off the Cobbler repo completely. I personally don't like big all-in-one repos and I think the frontend should not be in general a part of a core application.

#### Vanilla JS + Lightweight Web Framework (e.g. Flask)

Flask project homepage: https://flask.palletsprojects.com/en/1.1.x/

This may be a good alternative in my eyes if we don't want to focus on too much on the web frontend. If we want to have more in detail logic and a nice & easy looking GUI for new Cobbler users this will definitely get complicated as we have to write all of the code on our own.

#### Django

Project homepage: https://www.djangoproject.com/

This would be the most logical way I guess for most people. I don't have anything against Django but this would mean that we basically would have to redevelop Cobbler from scratch to fit the Django way of doing things.

This would in my eyes have the following consequences:

- We would definitely remove the "file"-database and depend on the Django ORM style mapping.
- We would be more GUI centric.
- This would mean a lot of incompatibilities to the "old" Cobbler.

#### Angular

Project homepage: https://angular.io/

This would certainly be a totally new way and would mean that we would need to scrap everything related to the web frontend. Why Angular? Well it is one of the biggest frameworks out there and thus may be the goto solution. What could be probably problematic is the speed of development and releases in Angular. The benefits are of course that we are very innovative this way.

#### React

Project homepage: https://reactjs.org/

This would certainly be a totally new way and would mean that we would need to scrap everything related to the web frontend. Why React? Well it is one of the biggest frameworks out there and I personally liked working with React.

#### No web frontend?

While I personally favor any kind of UI over a CLI with same feature set, I see that we currently don't have many active code contributors which can keep up with the progress of a fully featured web frontend technology and implementing these changes regulary.

### Additional context

This issue should be a collector of possibilities where everyone can decide for a solution or propose a new one.

Also I would like to give the input that I think the idea to make the web frontend easily themable (for example for usage in cooperations), is a point which I think would be a selling point in the future for Cobbler. I mean in a lab or at home it doesn't matter but having the ability to customize the frontend is a good thing in my eyes.

A last thought form me: Packaging Javascript applications is very painful for most of the distros but possible.

### Timeframe (if we do a new frontend)

I think this will be more precise if we have decided what to do with the frontend.

1. Develop the new frontend
2. Remove the old frontend

### Feedback

I would like to get feedback at least from:

- [x] @hbokh 
- [x] @brejoc 
- [ ] @watologo1 
- [x] @xenlo 
- [ ] @rbberger 
- [ ] @opoplawski 

Anyone else will of course heared with pleasure. The more opinions we have on this, the better in my eyes. I will close and lock this issue when I think it is the right point to decide something.

**Comment by SchoolGuy** [comment]
My personal opinion: I think we should go for either Django or Angular.

Django:

- We would keep this project Python-only
- We would get rid of problems like data integrity or references because we can take advantage of the ORM/database.

Angular:

- No dependencies to the core. Keeps the main repo frontend free.
- The frontend can be optionally deployed a lot easier and folks who don't need it can save themselves the cpu cycles. Currently parts of the frontend code are always installed.
- Less side effects and simpler testing of the core application. Also we can mock the the Cobbler-API and then test the frontend independently.

I think going for Angular is for me in the end the most favorable solution. We will need JS anyway, so why not use it from the very start. Having this inside Django could possibly just complicate things.

**Comment by davehodg** [comment]
I'm a huge fan of having a backend with API and a separate GUI on the front. Very good for testing and parallel development. You can easily snag a style from themeforest or similar.

**Comment by hbokh** [comment]
Django 1.1 is EOL since April 1st 2020. On our current Cobbler 3 I upgraded the package to Django 2.2 LTS without issue (on Debian 10 "Buster" with backports enabled, since that is where 2.2 is from).
So it looks like keeping Django is the _low hanging fruit_ option.

The current CSS used in "Cobbler web" can be easily refurbished to give it modern look. Here's what I did 3 years ago (though I'm not actually a web designer):

![Cobbler-web-20170531_1153](https://user-images.githubusercontent.com/519955/81807775-fc240d00-951e-11ea-8c8b-a86ba701f40b.png)

Keeping the webUI outside of the Cobbler core makes sense, but I am unfamiliar with the current available JS frameworks. Not sure how much work it will involve...

I came across this "cobbler-ui-part" some time ago, but it looks unmaintained: https://github.com/vanishcode/cobbler-ui-part

**Comment by brejoc** [comment]
First of all thanks to @SchoolGuy for kicking off this discussion! Then I'd also like to see feedback from @Conan-Kudo.

Okay, so here is the tl;dr part of my feedback: I'd also either vote for keeping but separating Django or AngularJS.

### Django
Actually I don't think Django is such a low hanging fruit. I think it's less work than Angular, but the current project structure is so horrible that we simply can't keep it like this. While Django doesn't follow the "convention over configuration" mantra too closely, those things exist and almost all Django application out there stick to this unless they have a really good reason to do it in another way. This allows people that are familiar with Django to navigate the code more easily. We don't have that in Cobbler. But I think it would be very beneficial to have.
Then we have to think about how to interface Cobbler. Do want to use the XML-RPC-API or should we just import the things we need… or do we want something in between? I'm not sure about this. while having a deep integration would allow us to do things quick, there would be no separation and a tiny change in Cobbler might break the Django application. On the other hand using XML-RPC would mean having more communication overhead, but might result in a more stable application.

@SchoolGuy You wrote that we would need to switch to a database to use Django. That is not entirely true. We would need a Database for sessions (and user management if we opt into this), but we are not forced to change the way Cobbler handles its data. Although it might be an option to change that in the future.

### AngularJS

This is of course a total rewrite of what we have. And in this case I'd say we should stick to XML-RPC to interface Cobbler. A good example for doing such a thing is Cloud Foundry's [Stratos UI](https://github.com/cloudfoundry/stratos). We could even steal some of their awesome stuff. The development of AngularJS might not be a wild ride anymore, but I'd argue that this is a pro instead of a con. I really wouldn't like to be forced to update this every two weeks only because it's not working with the next minor version bump. But I have to admit that I've only looked into AngularJS very briefly. It seems that Angular is more "batteries included" and that testing is baked right into the framework. These are aspects that appeal to me. Also I have the impression that integrating the web ui into other products would be easier with AngularJS. Please correct me if I'm wrong.

### React

Please don't! I have no problem with React in general, but I think it's just overkill for what we need. Actually I think we should stick to server side rendering entirely. Well, at least of we go for Django, Flask or something like that. If we need real time or push updates we can use things like [intercooler.js](https://github.com/intercoolerjs/intercooler-js) until we really, really need React for something like this. Server side rendering is easier to understand, easier to debug and only like 10 ms slower. We are not building the next Amazon or Facebook here. :wink: 

### Time and money

We also should consider those constraints when thinking about what to do. If we all like AngularJS, React or XYZ very much, but can't invest significant amounts of time for the rewrite, then we should stick to Django. Otherwise it would take much too long to get this ship off the ground. Just something to think about.

**Comment by Conan-Kudo** [comment]
The only realistic option is refactoring the Django app. Keep in mind that the other two options are not straightforward to package and we would need to do license audits for everything getting pulled in there, and that's no fun.

If we were to rewrite away from Django, I think the only reasonable alternative would be Flask. But Django is definitely suitable for what we need. I do agree the current Django web app structure is absolutely terrible, though.

**Comment by xenlo** [comment]
My experience with the Cobbler Web UI literally dates from 10 years ago… it was not a good memory. Actually at that moment I had the need to customize the views depending of the user (owner). And that wasn't possible (at that time at least) so I rewrote a entire web UI in PHP. 

➡️ So, I will definitively give a +1 for «_the ability to customize the frontend_».  But not only to change the aesthetic, but also the possibility to generate custom forms with limited fields, enforced value and/or limited list of value. To provide an interface to an operator to only create limited kind of system or edit only its own. But maybe that should be a separated issue.

About which tool/framework, in the list you provided, I'm only familiar with one: «_Django_»

➡️ So, I would give my +1 to an up to date Django  

I'm also quite familiar with «_No web frontend_», 😄 nevertheless, speaking about interface, I think that it could be advantageous to invest into an API REST (I don't know anything about XML-RPC). It could help having easy bridges and integration with other tools.

➡️ So, my +1 in investing some time in an API more that losing time to have a shining Web UI.

It's great to take time to ponder a bit. But as Cobbler is not a small project, and as it has not thousands of volunteer developers, I think that rate of effectiveness 'time VS improvement' should mostly guide the decisions…

**Comment by davehodg** [comment]
Please not XML. JSON please.

—
David Hodgkinson
Python/Perl Developer. DevOps.
Cardiff University.
daveh@hodgkinson.org
+44 7768 490620

**Comment by SchoolGuy** [comment]
Okay so to sum up I see currently the following options here:

- React is out of the picture.
- Having no WebUI is out of the picture.
- We want to concentrate on the Core and not have the most shiny WebUI ever made.
- No definite decision if we split the web frontend out of Cobbler or not.
- There were voices who wish for a REST-API with JSON. 
- JS only applications are problematic to package.

**Comment by SchoolGuy** [comment]
@Conan-Kudo Btw even if we use Django we will have JS dependencies so we will have the same problem also if we go full Django. I don't think we will just use pure native self written Javascript in the frontend...

**Comment by Conan-Kudo** [comment]
@SchoolGuy It's a lot more manageable than if you went with a fully JS frontend, though. We're not flooded with JavaScript now, for example.

**Comment by brejoc** [comment]
@Conan-Kudo Btw, how is Fedora handling this? Everything (like jquery for example) needs a separate package, or is it possible to have it included in the Cobbler Django project?

**Comment by Conan-Kudo** [comment]
It's _preferred_ to split them out, but nowadays you can just bundle it and have `bundled()` Provides for the JS you include, per [the policy](https://fedoraproject.org/wiki/Bundled_Libraries#Requirement_if_you_bundle).

**Comment by davehodg** [comment]
Definitely REST API wirg JSON.

Splitting the frontend and backend gives you two packages which I think has benefits.

I don't see how JS only is problematic provided the deps are packaged. No need for usinf a JS packager.

**Comment by SchoolGuy** [comment]
To summarize what my current understanding of the votes so far is:

We have basically have two approaches

1. Django
2. Remove Django, Add Flask with REST JSON API + Angular Frontend

I am currently in another project tangling with Django and I am drifting more and more towards option two for Cobbler. If I count this correctly, @Conan-Kudo raised concerns regarding the packaging of the frontend because of the JS dependencies but no one else objected the second proposal.

To make things not more complicated I would say that until the end of the week we leave this open and if I don't get any arguments except making the packaging more complicated, I would say we have a common agreement on option two.

**Comment by Conan-Kudo** [comment]
It's not just the complication of JS dependencies, all those dependencies need license auditing and enumeration if we're bundling, or they need to be packaged up separately.

Nothing about what you're trying to do necessarily _requires_ Angular. So I'm confused as to why you want _that_ specifically. You could just as easily do a Flask app and build a frontend that is minimal on the JS as well.

**Comment by SchoolGuy** [comment]
Angular has a great community, we have many pieces of code already prepared and thus we just need to care about the data and the layout. We have backed in testing and we have frequent updates. For Angular thus it is very likely that all those things you say are already done. If we write all the JS Code for ourselves, i fear that we burden ourselves with a great deal of work which we will spare us if we choose a framework. Angular just happened to be the one I personally know and I am sure where everything we will encounter is covered. Also I am sure that Angular is not a JS framework which will be out of "fashion" in a few months since it is backed by Google.

If there is another framework which meets all above points I am happy to go for an easier one which will require less work or has other benefits over Angular.

**Comment by SchoolGuy** [comment]
So it is decided:

- Remove from this repo in a future version the Django components
- Add an HTTP REST API additionally with Flask
- Create a new frontend based on Angular
