### ISSUE TITLE
cobbler.conf and cobbler_web.conf are installed in /etc/cobbler as well

### ISSUE THREAD

**Issue by opoplawski** [cobbler/cobbler#2358]
### Describe the bug

When building the Fedora RPM, cobbler.conf and cobbler_web.conf are installed in /etc/cobbler as well as /etc/httpd/conf.d.  They shouldn't be.

**Comment by SchoolGuy** [comment]
If we install via `setup.py` we don't know if anyone maybe has an nginx server installed or no Apache2 at all. Thus I don't think we can generally install it in the web directory of `/etc/httpd/conf.d`.

Since installing in our own directory is done in `setup.py` we would need to (re)move the file to the webserver config dir.

**Comment by opoplawski** [comment]
Okay, I kind of forgot about the `pip install cobbler`, assuming that is still a thing.  But if someone has the sources they can just copy from there.  We definitely remove the files in cobbler.spec - that's what triggered me to wonder why.
