### ISSUE TITLE
Cobbler should work with external proxy

### ISSUE THREAD

**Issue by Dreamfire73** [cobbler/cobbler#2472]
### Describe the bug

Unable to use commands such as "cobbler get-loaders" or "cobbler signature update" while using proxy in  /etc/cobbler/settings

### To Reproduce

1. Go to /etc/cobbler/settings and reference external proxy ` proxy_url_ext: "http://my.proxy.fr:port"`
2. Restart cobblerd and do `cobbler sync` 
3. Do `cobbler get-loaders`
4. Error occured without updating loaders (see screenshot attached)
[error.txt](https://github.com/cobbler/cobbler/files/5696118/error.txt)
![Capture](https://user-images.githubusercontent.com/72204474/102219960-77e49e80-3ee0-11eb-9b8d-e23e66ec7be0.PNG)

### Expected behavior

Loaders get updated without error

### Version

Cobbler version : 
`Cobbler 3.2.0
  source: b'62b51194', b'Wed Dec 9 11:59:41 2020 +0100'
  build time: Tue Dec 15 10:31:55 2020`

Python Version :
`Python 3.7.3`

**Comment by SchoolGuy** [comment]
This has some greater implications because we need to check the whole code for downloading stuff from remotes and thus then adjusting this to be downloaded via the proxy. But thanks for spotting and reporting! Sorry for the inconvenience...

**Comment by razorbladex401** [comment]
any update on this or any workaround for this? trying to setup cobbler in an environment that has no direct internet access and facing the same problem.

**Comment by SchoolGuy** [comment]
So `cobbler get-loaders` was removed due to the fact that we can't provide safe and signed bootloaders. The effort is just too much. Thus for this subcommand there won't be any solution. The upcoming release 3.3.0 won't have a solution for the general problem. This is currently a two man show and we deemed DHCPv6 support the most important thing for now. However the refactorings going on behind the scenes are making room for tickets like this to be resolved in the future much quicker. I am very sorry that things tend to take a lot of time in this project.
