### ISSUE TITLE
Move CI from Travis to Github Actions

### ISSUE THREAD

**Issue by dansou901** [cobbler/cobbler#2507]
As discussed in #2422, we need a new CI System. Just opening this issue to continue discussing the new infrastructure. My proposal would be:
* have traefik already configured on a docker host via compose with let's encrypt for certificates
* also use compose to spin up jenkins behind that mentioned traefik
* have a live instance and a backup instance which is only started manually when the live instance has problems
* use the same email address for let's encrypt for both the live instance and the backup instance

**Comment by SchoolGuy** [comment]
So my home setup will be (I am in the process of moving away from a professional hoster as I don't want to spend that money):

- Traefik in Docker
- Docker Containers behind that Proxy via Let's Encrypt

Since I only have 8GB of RAM and 4 Cores (for now) and I don't want to use Docker Swarm (my setup wouldn't work with Swarm), I thought about having a K3s Raspi Cluster and deploying Jenkins to that. My main server then would server as an additional proxy and SSL terminate the traffic there. The new 4B Models have 8GB of RAM and a modest CPU. If I would have 4 of them, we would have a cheap and decent cluster. The reason why I am hesitating to deploy Jenkins directly on my main server is that there is already running ~15 Containers (NC, Websites, ...).

Also I gave the backup cluster a thought... I havn't had downtimes in network and power for the last 5 years which were severe. Those few times where I was down, it was either a regional loss of internet which lasted only a few hours or my ISP fucked it up. Power Outages only last about less then half an hour. I think since I am rarely down, I would love if we could spare us the work of having a backup cluster. It's not about not wanting to have it but more about the benefit (or more the lack of it) which I think is there.

We have a project which is not dependent on delivering work in a matter of hours of minutes. If I am down, we wait for a day and then I rerun the pipeline. At least that is my opinion.

@opoplawski @hbokh @brejoc @gregswift @xenlo Do you have opinions on that. I know that most of you are using it in prod and thus I would love to include you here!

**Comment by dansou901** [comment]
If you want to do a K3S Raspi Cluster, do that. Then I don't think that we need a backup cluster. That was just in case you planned to have it running next to your home setup on your existing server. But having code as infrastructure for the Raspi Cluster is a good idea anyway, so we should have that living in separate repositories, maybe even private ones where only we have access. That way, if anything goes wrong, you can restore the cluster from a pipeline if needed.

**Comment by dansou901** [comment]
On the Raspi Cluster you can then use https://github.com/jenkinsci/helm-charts to install jenkins.

**Comment by SchoolGuy** [comment]
@dansou901 Thanks for the hint. I will do so immediately when my parts are there. I guess latest end of January we can expect that I can start working on that Jenkins Instance of mine...

**Comment by SchoolGuy** [comment]
Since the Gitter discussion brought no storms of enthusion but rather eyebrow rasing and we have our first "could-been-prevented-by-CI" problem, I will now port Travis to Github Actions.

**Comment by SchoolGuy** [comment]
Jenkins is not from the table but my parts are not ready at home and thus we will use Github Actions as Long as reasonable possible.

**Comment by SchoolGuy** [comment]
Github offers to self host runners. Thus I think Github Actions are far better because we just host the runners and are done. @dansou901 do you think the same, or do you think Jenkins would offer us more?

**Comment by dansou901** [comment]
We are currently migrating to Github, so it's best to stay at it for the time being, at least until Gitlab supports forks. If we still want to self host until then, we should stay at Github Actions (following the keep it simple principle).
