### ISSUE TITLE
Independence from service

### ISSUE THREAD

**Issue by SchoolGuy** [cobbler/cobbler#2612]
### Is your feature request related to a problem?

Currently we have explicit hardcoded calls to `service NAME restart` and other similar commands. This means if we run in a docker environment we will ultimately fail.

### Provide a detailed description of the proposed feature

I desire that we support:

- `service`
- `systemd`
- `supervisord`

for process management. The last two systems have APIs available which will make us independent of the current host or the ties to a real system.

### Alternatives you've considered

Hardcoding is not an option. A library does not exist to my knowledge to support service restarts across different types of process managers.

### Additional information

- [SupervisorD API Docs](http://supervisord.org/api.html)
- [SystemD API](https://github.com/systemd/python-systemd)

**Comment by th-2021** [comment]
Is there a reason, why services are restarted in
./modules/sync_post_restart_services.py
as well as in the corresponding managers
modules/managers/bind.py

Should this service restart not end up in utils.py, so that we can distinguish between the different implementations in just one place (service/systemd/supervisord)

**Comment by SchoolGuy** [comment]
Yes in theory that would be great. So far this is mostly legacy code, so a cleanup wouldn't hurt. We just havn't had the time to clean this up yet. If you want to give it a try @th-2021 , please do so!
