### ISSUE TITLE
cobbler v3.2   cobbler  esxi error

### ISSUE THREAD

**Issue by leon123go** [cobbler/cobbler#2829]
### Describe the bug
![image](https://user-images.githubusercontent.com/34236101/139618176-e7b845ab-faa3-4480-bf09-387142a66ae6.png)

![image](https://user-images.githubusercontent.com/34236101/139618120-7dfe97af-b3aa-4992-b56b-e3382bd6b787.png)

There was a problem loading

### Cobbler version
3.2

### Operating system
CentOS Stream release 8

### Cobbler log

````paste below
````

### Additional information
iso= esxi 6.7

**Comment by SchoolGuy** [comment]
@leon123go Which Cobbler 3.2 version do you use?

I believe that the error here is not in Cobbler but the error is either in ESXi or in the setup you have. What we see here is that the kernel is rejected by GRUB since it has an invalid magic number. This is possible due to various reasons I can't pinpoint now but maybe the ISO you have is corrupt? Light googling suggest that this is the most common error source in such a case.

**Comment by heroin-moose** [comment]
Also check your boot mode. Is it legacy or UEFI?

**Comment by leon123go** [comment]
> @leon123go Which Cobbler 3.2 version do you use?
> 
> I believe that the error here is not in Cobbler but the error is either in ESXi or in the setup you have. What we see here is that the kernel is rejected by GRUB since it has an invalid magic number. This is possible due to various reasons I can't pinpoint now but maybe the ISO you have is corrupt? Light googling suggest that this is the most common error source in such a case.

![image](https://user-images.githubusercontent.com/34236101/139999383-3e275b3e-fbe2-4cea-a1a7-1461de227bac.png)
 I use vmware to test and install iso exsi6.7 is ok, but cobbler can’t

**Comment by leon123go** [comment]
> Also check your boot mode. Is it legacy or UEFI?
How can I verify the UEFI I am using?

**Comment by leon123go** [comment]
> ISO
