### ISSUE TITLE
Can't install on Ubuntu 20.04 - unknown tag py3_build

### ISSUE THREAD

**Issue by holmesb** [cobbler/cobbler#2893]
```
$ sudo make debs
<snip>
Unknown tag '%py3_build' at line 306 of cobbler.spec
make: *** [Makefile:180: debs] Error 255
```
py3_build was [deprectated](https://docs.fedoraproject.org/en-US/packaging-guidelines/Python/#_deprecated_macros), probably now removed.

**Comment by SchoolGuy** [comment]
Okay this is madness. They changed all the macros which were compatible on both openSUSE AND Fedora. I believe we indeed need to fix this and before the next release, so we can build also outside of the OBS...

**Comment by maxadamo** [comment]
@SchoolGuy you need to narrow the scope of the project and try to make everything work. 
Apologies for being direct, but everything is borked, and you're adding Angular frontend, you add configuration management features (such as templates), but nothing is really working and you mark the releases as stable. 

Please create Alpha and Beta releases.

**Comment by SchoolGuy** [comment]
@maxadamo The creator of this project (not me) did start this project before he started Ansible. Thus it is actually the other way around... ;)

Anyway. I agree that I have to make everything work but since I didn't add too many features in the last years and kept trying to stabilize what was there I don't see that I have to narrow things down. I just have to take time and do the things that need to be done. Arguably there are a lot of things to do but thankfully this is open source and I don't have to do everything on my own. If you want it to be better feel free to become a regular contributor, I am happily sending anyone an invite who shows me regular contributions to the project.

**Comment by SchoolGuy** [comment]
I will close this in favour of #2393. It doesn't help to fix something that is anyway going to be removed in the same release.
