### ISSUE TITLE
Modifying the dhcp.template for shared-lom throwing errors

### ISSUE THREAD

**Issue by Shubhangi-dell** [cobbler/cobbler#3028]
### Describe the bug
I am using cobbler 3.2.2 on rocky 8.5.
I have a shared-lom setup and I wanted the cobbler to manage the DHCP. So, I have made the required changes in dhcp.template and tried to run cobbler sync. I have adhered to the documentation and haven't changed anything from **#for dhcp_tag in $dhcp_tags.keys():** The error is attached below:
![image](https://user-images.githubusercontent.com/72869337/163388588-5d0e2a1a-6e9a-4d54-ad7c-2ecad31cc774.png)
My dhcp.template looks like this: https://gist.github.com/Shubhangi-dell/64d5fa442f820dd1327193db690394b0
Cobbler and all other related services are running.

Also, when running dhcp individually on the host, the same dhcpd.conf works fine and I am able to assign IP in a shared lom network.
Even dhcp -t isn't giving any error and I have all the required IPs from multiple subnets in dhcpd.leases.

### Steps to reproduce
1. Run cobbler in shared-lom
2. In settings.yaml set manage_dhcp: true
3. Restart and run cobbler sync

### Expected behavior
Dhcp should run properly.

### Cobbler version
3.2.2

![image](https://user-images.githubusercontent.com/72869337/163390760-a82ba77e-fc18-4cd1-bde0-f188a984cde1.png)

### Operating system
Rocky 8.5

**Comment by SchoolGuy** [comment]
So I can see multiple problems in the template:

- https://gist.github.com/Shubhangi-dell/64d5fa442f820dd1327193db690394b0#file-gist-github-com-L16
  Here I would suggest or something similar. The reason the Cheetah Line doesn't work is because this is a Python `str` at some point and the quotation for it is missing. In case this should be a comment please use `##`
  ```
  #set vendorclass = "option vendor-class-identifier";
  ```
- https://gist.github.com/Shubhangi-dell/64d5fa442f820dd1327193db690394b0#file-gist-github-com-L50
  For a while now `next_server` was renamed to `next_server_v4` and `next_server_v6`. So this has to be adjusted

After those two changes things should be better already.

Maybe consult the Cheetah Language Spec for further details about the syntax: https://cheetahtemplate.org/users_guide/language.html#language-constructs-summary

**Comment by Shubhangi-dell** [comment]
Hi,
Thanks it worked. The 1st point was the issue in my case. Since, I am using an older version of cobbler i.e. 3.2.2 I don't need to update it to next_server_v4.
