### ISSUE TITLE
Add support for CentOS Stream 9 and RHEL9

### ISSUE THREAD

**Issue by PhilEv** [cobbler/cobbler#3068]
### Is your feature request related to a problem?

This is an enhancement for the support of CentOS Stream 9 and RHEL 9

### Provide a detailed description of the proposed feature

Currently (using version 3.2.2 and the WEB UI is needed) it is not possible/supported  to import and deploy a CentOS Stream 9 (and the coming RHEL9).
 
To make it work one need to
- For `cobbler import` update the `/var/lib/cobbler/distro_signatures.json` file (or the one from the `signature_path` cobbler setting) with a RHEL9 entry like the below:
  ```json
       "rhel9": {
        "signatures": [
          "BaseOS"
        ],
        "version_file": "(redhat|sl|slf|almalinux|centos|centos-linux|centos-stream|oraclelinux|rocky|vzlinux)-release-(?!notes)([\\w]*-)*9[\\.-]+(.*)\\.rpm",
        "version_file_regex": null,
        "kernel_arch": "kernel-(.*).rpm",
        "kernel_arch_regex": null,
        "supported_arches": [
          "i386",
          "x86_64",
          "ppc",
          "ppc64",
          "ppc64le"
        ],
        "supported_repo_breeds": [
          "rsync",
          "rhn",
          "yum"
        ],
        "kernel_file": "vmlinuz(.*)",
        "initrd_file": "initrd(.*)\\.img",
        "isolinux_ok": false,
        "default_autoinstall": "sample.ks",
        "kernel_options": "",
        "kernel_options_post": "",
        "boot_files": []
      },
  ```
- remove the `install` directive from the `/var/lib/cobbler/templates/sample.ks` file
  or any other similar files in the  directory referenced by the  `autoinstall_templates_dir` cobbler setting 

- make sur that any generated  tftpboot file  in `/var/lib/tftpboot/pxelinux.cfg`  or `/var/lib/tftpboot/pxelinux.cfg\grub/system/` 
  always uses the `inst.` prefix  that is mandatory for el9 and clones for any parameter passed to the boot kernel includind the `kssendmac` that should be `inst.kssendmac`. 

  That is in the various configuration file generated in the directory referenced by the `tftpboot_location` cobbler setting  
  (similarly to the inst.ks related PR https://github.com/cobbler/cobbler/pull/2534 )

**Comment by PhilEv** [comment]
@SchoolGuy for the part related to item 3 above and looking at the code, 

patching [tftpgen.py ](https://github.com/cobbler/cobbler/blob/main/cobbler/tftpgen.py) 

plus  
https://github.com/cobbler/cobbler/blob/main/cobbler/actions/buildiso/standalone.py and https://github.com/cobbler/cobbler/blob/main/cobbler/actions/buildiso/netboot.py 

for breed == "redhat"  should be enough.

I will make an attempt and come back with a better proposal.

**Comment by SchoolGuy** [comment]
@PhilEv Thanks a lot!

**Comment by PhilEv** [comment]
@SchoolGuy 

leaving aside for now [standalone.py](https://github.com/cobbler/cobbler/blob/main/cobbler/actions/buildiso/standalone.py) and [netboot.py](https://github.com/cobbler/cobbler/blob/main/cobbler/actions/buildiso/netboot.py) after patching  my cobbler dev system (3.3.2) `tftpgen.py` (see below) and with the 2 other modifications already described
I've been able to import a CentOS Stream9 and deploy a system with it (pxe boot)

```bash
$ diff tftpgen.py tftpgen.py.origin 
733c733
<                 append_line += " inst.kssendmac"
---
>                 append_line += " kssendmac"
```

What is your suggestion for a PR against branch `release32`  to start with (aka the one I'm interested in) ?
what amount of test to run to get it accepted ? any pointer here will help

retrofitting to other branches should be quite obvious or not that hard.

**Comment by SchoolGuy** [comment]
@PhilEv If you submit against `release32` then the only thing you need is that you open a PR against it. The CI takes care of the testing. If you test stuff via the GitHub Actions CI, just cleanup the Git history before asking for a review. Everything else you might need help with should be describes here: https://github.com/cobbler/cobbler/wiki if there is something missing in the Wiki please ping me. The instructions about `pre-commit` and Black is not important for 3.3.x or older so you can skip that.

**Comment by NileshChandekar** [comment]
#### Cobbler Server Details:
~~~
Rocky Linux release 8.9 (Green Obsidian)
~~~

~~~
[root@localhost rhel9-x86_64]# cobbler --version
Cobbler 3.2.2
  source: ?, ?
  build time: Wed Apr  5 15:54:53 2023
[root@localhost rhel9-x86_64]# 
~~~
 
* OK, so after some investigation identify that, 
* cobbler import is failing due to 
* not having the proper dir structure. 

~~~
[root@localhost distro_mirror]# cobbler import --arch=x86_64  --path=/mnt --name=rhel9
task started: 2024-03-08_075202_import
task started (id=Media import, time=Fri Mar  8 07:52:02 2024)
running python triggers from /var/lib/cobbler/triggers/task/import/pre/*
running shell triggers from /var/lib/cobbler/triggers/task/import/pre/*
shell triggers finished successfully
Found a candidate signature: breed=suse, version=opensuse15.0
Found a candidate signature: breed=suse, version=opensuse15.1
Found a candidate signature: breed=suse, version=opensuse15.2
Found a candidate signature: breed=suse, version=opensuse15.3
Found a candidate signature: breed=suse, version=opensuse15.4
Found a candidate signature: breed=suse, version=sles15generic
No signature matched in /var/www/cobbler/distro_mirror/rhel9-x86_64
Exception occurred: <class 'cobbler.cexceptions.CX'>
Exception value: 'No signature matched in /var/www/cobbler/distro_mirror/rhel9-x86_64'
Exception Info:
  File "/usr/lib/python3.6/site-packages/cobbler/remote.py", line 98, in run
    rc = self._run(self)

  File "/usr/lib/python3.6/site-packages/cobbler/remote.py", line 286, in runner
    self.logger

  File "/usr/lib/python3.6/site-packages/cobbler/api.py", line 1476, in import_tree
    import_module.run(path, mirror_name, network_root, autoinstall_file, arch, breed, os_version)

  File "/usr/lib/python3.6/site-packages/cobbler/modules/managers/import_signatures.py", line 195, in run
    raise CX(error_msg)

!!! TASK FAILED !!!
[root@localhost distro_mirror]# 
~~~


~~~
[root@localhost distro_mirror]# ls -lhrt /var/www/cobbler/distro_mirror/rhel9-x86_64/
total 4.0K
drwxrwxr-x 2 root root 4.0K Apr 13  2023 isolinux
drwxrwxr-x 3 root root   18 Apr 13  2023 EFI
drwxrwxr-x 3 root root   59 Apr 13  2023 images
[root@localhost distro_mirror]# 
~~~

* Checking the signature

~~~
      "rhel9": {
        "signatures": [
          "BaseOS"
~~~

* Do not see BaseOS dir in the distros. 

* RHEL-9 do not have minimal iso
* RHEL-9 comes with 2 iso:- 
  * boot.iso
  * dvd.iso
* boot.iso do not have BaseOS or Minimal dir structure. 

#### WORKAROUND

* Mount DVD and Copy 
* BaseOS and Minimal dir. 
* Import should work 

~~~
[root@localhost rhel9-x86_64]# ls
BaseOS  EFI  images  isolinux  minimal
[root@localhost rhel9-x86_64]# 
~~~

~~~
[root@localhost rhel9-x86_64]# cobbler import --arch=x86_64  --path=/mnt --name=rhel9
task started: 2024-03-08_080347_import
task started (id=Media import, time=Fri Mar  8 08:03:47 2024)
running python triggers from /var/lib/cobbler/triggers/task/import/pre/*
running shell triggers from /var/lib/cobbler/triggers/task/import/pre/*
shell triggers finished successfully
Found a candidate signature: breed=redhat, version=rhel8
Found a candidate signature: breed=redhat, version=rhel9
Found a matching signature: breed=redhat, version=rhel9
Adding distros from path /var/www/cobbler/distro_mirror/rhel9-x86_64:
creating new distro: rhel9-x86_64
trying symlink: /var/www/cobbler/distro_mirror/rhel9-x86_64 -> /var/www/cobbler/links/rhel9-x86_64
creating new profile: rhel9-x86_64
associating repos
checking for rsync repo(s)
checking for rhn repo(s)
checking for yum repo(s)
starting descent into /var/www/cobbler/distro_mirror/rhel9-x86_64 for rhel9-x86_64
processing repo at : /var/www/cobbler/distro_mirror/rhel9-x86_64/BaseOS
directory /var/www/cobbler/distro_mirror/rhel9-x86_64/BaseOS is missing xml comps file, skipping
processing repo at : /var/www/cobbler/distro_mirror/rhel9-x86_64/minimal
directory /var/www/cobbler/distro_mirror/rhel9-x86_64/minimal is missing xml comps file, skipping
*** TASK COMPLETE ***
[root@localhost rhel9-x86_64]#
~~~
