### ISSUE TITLE
invalid value for 'inst.rep' $tree

### ISSUE THREAD

**Issue by fwt11** [cobbler/cobbler#3417]
### Describe the bug

OS Installation stops with  warnings "invalid value for 'inst.rep' $tree" and "/dev/root does not exit"

### Steps to reproduce

the content of `/var/lib/tftpboot/pxelinux.cfg/default` generated by cobbler is 

```
DEFAULT menu

PROMPT 0
MENU TITLE Cobbler | https://cobbler.github.io
TIMEOUT 200
TOTALTIMEOUT 6000
ONTIMEOUT local

LABEL local
        MENU LABEL (local)
        MENU DEFAULT
        LOCALBOOT -1

LABEL centos7.9-x86_64
        MENU LABEL centos7.9-x86_64
        kernel /images/centos7.9-x86_64/vmlinuz
        append initrd=/images/centos7.9-x86_64/initrd.img  kssendmac inst.ks=http://192.168.100.123:8080/cblr/svc/op/autoinstall/profile/centos7.9-x86_64
        ipappend 2
MENU end
```

if i manually add 
`inst.repo="http://192.168.100.123:8080/cblr/distro_mirror/centos7.9"` after the 'initrd.img'
the installation will continue.
### Expected behavior

i remember that inst.repo is  generated by cobbler automatically in 2.x version. 

### Cobbler version
3.3.3

````paste below
````

### Operating system

fedora 38
### Cobbler log

````paste below
````

### Screenshots

![截图_virt-manager_20230427134528](https://user-images.githubusercontent.com/5778894/234777045-b9995f3b-b2bf-4941-b7e9-5a61b6b93b33.png)

![截图_选择区域_20230427134653](https://user-images.githubusercontent.com/5778894/234772218-b77627c3-c309-4eae-a3f2-8dc82fff2e9a.png)

**Comment by wenzi0729** [comment]
I had the same problem

**Comment by jackylee** [comment]
I have the same problem, fedora 38.
![image](https://github.com/cobbler/cobbler/assets/167346/62f423cc-2ed3-4471-9f9f-419a14e38001)

**Comment by brasslan** [comment]
+1 for me.   I'm also having this problem with cobbler-3.3.3-7.fc39.noarch   (currently, Fedora39 is in Beta).

THANK YOU SO MUCH FWT11 after your instructions to manually add the inst.repo kernel option. 
 aka inst.repo="http://192.168.100.123:8080/cblr/distro_mirror/centos7.9"   Now, I have had my very first successful PXE install of Rocky 8 because of you.  I've been trying SSSOOOO many things without success.   I've tried multiple OS to install cobbler to (fedora 36/37/38/39 Rocky8/9 CentOS8, and multiple OS to deploy from cobbler and nothing seems to work for me and since I'm brand new to PXE, and kickstart, and kernel options, I'm having a lot of trouble figuring out things like inst.repo that break the system.  The only reason I'm trying to PXE install Rocky 8 is because there are too many bugs in cobbler preventing Rocky 9 installs.  Again, the kernel options are not correct, and I don't yet know how to fix them.  But now that I've got a work around for this one, I've got some pretty good ideas on what to try next.

One problem that I'm having with EL8 or EL9 is the Network install path in the $tree isn't correct.  I don't know what $tree is, or where to fix this.  For the Rocky 8 install above, it wasn't an automatic install (which would be broken), but instead it let me go through the install process (first time I've done it in all text).  And during the install, I was able to change the install location to http://10.224.57.56/cblr/distro_mirror/Rocky8-x86_64 so that it could find my packages and install.  And after many MANY hours troubleshooting this, I'm pretty excited that I was able to do my first network install.  I'm going to keep at it until I get automated installs of Rocky 8/9, and Windows 10/11.

**Comment by zparihar** [comment]
Hi,  
Sorry.  I filed another bug and Workaround at:
https://github.com/cobbler/cobbler/issues/3493

**Comment by SchoolGuy** [comment]
So the interesting part is that the code to set the value is still present. It seems the code is just not called. I will debug this tomorrow. The import action desires some love in general though...

**Comment by SchoolGuy** [comment]
So with the code in the linked Pull Request, I was not able to reproduce that autoinstall-meta is missing `tree`. I was however able to reproduce that `inst.repo` is missing. I will fix this on `main` and try and double-check how the situation is with release33.

**Comment by SchoolGuy** [comment]
This issue is a little tricky to fix since there is the following problem:

- Adding the kernel options in `distro_signatures.json` would mean that `cobbler buildiso --standalone` would be broken for RH-based distros.
- Adding the kernel options in `tftpgen.py` would mean that a network bootable ISO wouldn't receive them, leading to inconsistencies.
- Adding the kernel options in both `tftpgen.py` and `buildiso/netbooth.py` would mean we are adding even more duplication for kernel options generation. On the other hand, keeping them separate makes sense since the generators perform different duties.

**Comment by SchoolGuy** [comment]
During an afternoon walk, I concluded that in the interest of being able to backport this the most reasonable option is to duplicate the logic for all three use cases. They differ quite a bit and as such it makes sense to keep the code separate. If it makes sense in the end to consolidate the append line generation of the use cases we can do that after we have released 3.4.0.

This means we need modification for the following files:

- `cobbler/tftpgen.py`
- `cobbler/actions/buildiso/netboot.py`
- `cobbler/actions/buildiso/standalone.py`

Actually testing a complete auto-installation is not possible in GitHub Actions and as such I need to test the new code once manually and freeze the result of `pxelinux.cfg/default` and match its output with the generate one from the code in the pipeline.

**Comment by SchoolGuy** [comment]
I am by all means no RedHat expert. I believe that the equivalent of `inst.repo` was `repo`. Feel free to correct me if I am wrong.

**Comment by SchoolGuy** [comment]
So my computer at home sadly pulls double duty and as such I don't have enough RAM for additional virtual machines. I will test my PR at work tomorrow but I am mainly relying on anyone in the community to test my PR. I don't have access to RedHat media and legally - afaik - will never be able to get access since I am working for SUSE. I will however try and verify this with another RedHat breed distro.

**Comment by lejeczek** [comment]
I've _grabbed_ **main** today and dropped it in in place on Centos .tar - there it distro-builds fine - **cobbler** import of Centos 9 and...
I do get:
`Warning: Invalid value for 'inst.repo': $tree`

**Comment by opoplawski** [comment]
Well, the fix isn't in main yet. You are either going to need to apply the change from the pull request or build from https://github.com/cobbler/cobbler/tree/fix/add-tree-auto-install-meta

**Comment by opoplawski** [comment]
After battling the cobbler import issue introducted by the PR, I do see inst.repo= being added to the pxeboot in pxelinux.cfg/default:
```
        append initrd=/images/centos-stream-9-x86_64/initrd.img  inst.ks.sendmac inst.ks=http://127.0.0.1/cblr/svc/op/autoinstall/profile/centos-stream-9-x86_64 inst.repo=http://127.0.0.1/cblr/links/centos-stream-9-x86_64
```
However, I think it still needs to get added to the profile based boot options in the grub.cfg and isolinux.cfg files for the iso:
```
/mnt/EFI/BOOT/grub.cfg:  linux /1.krn  inst.ks=http://127.0.0.1:80/cblr/svc/op/autoinstall/profile/fedora-38-x86_64
/mnt/EFI/BOOT/grub.cfg:  linux /2.krn  inst.ks=http://127.0.0.1:80/cblr/svc/op/autoinstall/profile/centos-stream-9-x86_64
/mnt/EFI/BOOT/grub.cfg:  linux /1.krn  inst.ks=http://127.0.0.1:80/cblr/svc/op/autoinstall/system/rawhide inst.repo=http://download.fedoraproject.org/pub/fedora/linux/releases/38/Everything/x86_64/os/
/mnt/EFI/BOOT/grub.cfg:  linux /1.krn  inst.ks=http://127.0.0.1:80/cblr/svc/op/autoinstall/system/test inst.repo=http://download.fedoraproject.org/pub/fedora/linux/releases/38/Everything/x86_64/os/
/mnt/EFI/BOOT/grub.cfg:  linux /1.krn  inst.ks=http://127.0.0.1:80/cblr/svc/op/autoinstall/system/cs9 inst.repo=http://download.fedoraproject.org/pub/fedora/linux/releases/38/Everything/x86_64/os/
/mnt/isolinux/isolinux.cfg:  append initrd=/1.img inst.ks=http://127.0.0.1:80/cblr/svc/op/autoinstall/profile/fedora-38-x86_64
/mnt/isolinux/isolinux.cfg:  append initrd=/2.img inst.ks=http://127.0.0.1:80/cblr/svc/op/autoinstall/profile/centos-stream-9-x86_64
/mnt/isolinux/isolinux.cfg:  APPEND initrd=/1.img inst.ks=http://127.0.0.1:80/cblr/svc/op/autoinstall/system/rawhide inst.repo=http://download.fedoraproject.org/pub/fedora/linux/releases/38/Everything/x86_64/os/
/mnt/isolinux/isolinux.cfg:  APPEND initrd=/1.img inst.ks=http://127.0.0.1:80/cblr/svc/op/autoinstall/system/test inst.repo=http://download.fedoraproject.org/pub/fedora/linux/releases/38/Everything/x86_64/os/
/mnt/isolinux/isolinux.cfg:  APPEND initrd=/1.img inst.ks=http://127.0.0.1:80/cblr/svc/op/autoinstall/system/cs9 inst.repo=http://download.fedoraproject.org/pub/fedora/linux/releases/38/Everything/x86_64/os/
```

**Comment by SchoolGuy** [comment]
@opoplawski Thanks for the feedback. I will try and get the import error fixed as well as adding this to the remaining files.

**Comment by SchoolGuy** [comment]
@opoplawski I tried reproducing the errors that I thought I had but wasn't able to. Can you please remind me how to reproduce the import error? I think with the rebase and force push I was able to solve the profile-based kernel command line.

**Comment by opoplawski** [comment]
The import issue I faced was that any distro that was imported from an installer ISO was missing the autoinstall_meta tree variable.  It doesn't look like you have addressed the problematic change to import_signatures.py so the issue should still be present.

**Comment by opoplawski** [comment]
Any progress here?

**Comment by SchoolGuy** [comment]
@opoplawski I got my computer at home finally some new RAM which means I can now test the change without freezing up my whole system. I will try and get `tree` automatically added to the dict again today.

**Comment by SchoolGuy** [comment]
I identified the bug: We are using properties. In this scenario, we are returning a copy of a dict that contains the resolved view of the distro. This means we are updating this resolved copy and not the actual raw value (which we intended). We are having a similar problem with other properties as well it seems.

With my local fixup I am now seeing the value. I just need to find a clean way to integrate it.

**Comment by opoplawski** [comment]
Looks good to me now:
```
# grep -rF inst. /mnt
/mnt/EFI/BOOT/grub.cfg:  linux /1.krn  inst.ks=http://127.0.0.1:80/cblr/svc/op/autoinstall/profile/fedora-38-x86_64 inst.repo=http://download.fedoraproject.org/pub/fedora/linux/releases/38/Everything/x86_64/os/
/mnt/EFI/BOOT/grub.cfg:  linux /2.krn  inst.ks=http://127.0.0.1:80/cblr/svc/op/autoinstall/profile/centos-stream-9-x86_64 inst.repo=http://127.0.0.1/cblr/links/centos-stream-9-x86_64
/mnt/EFI/BOOT/grub.cfg:  linux /3.krn  inst.ks=http://127.0.0.1:80/cblr/svc/op/autoinstall/profile/cs9test-x86_64 inst.repo=http://127.0.0.1/cblr/links/cs9test-x86_64
/mnt/EFI/BOOT/grub.cfg:  linux /1.krn  inst.ks=http://127.0.0.1:80/cblr/svc/op/autoinstall/system/rawhide inst.repo=http://download.fedoraproject.org/pub/fedora/linux/releases/38/Everything/x86_64/os/
/mnt/EFI/BOOT/grub.cfg:  linux /1.krn  inst.ks=http://127.0.0.1:80/cblr/svc/op/autoinstall/system/test inst.repo=http://download.fedoraproject.org/pub/fedora/linux/releases/38/Everything/x86_64/os/
/mnt/isolinux/isolinux.cfg:  append initrd=/1.img inst.ks=http://127.0.0.1:80/cblr/svc/op/autoinstall/profile/fedora-38-x86_64 inst.repo=http://download.fedoraproject.org/pub/fedora/linux/releases/38/Everything/x86_64/os/
/mnt/isolinux/isolinux.cfg:  append initrd=/2.img inst.ks=http://127.0.0.1:80/cblr/svc/op/autoinstall/profile/centos-stream-9-x86_64 inst.repo=http://127.0.0.1/cblr/links/centos-stream-9-x86_64
/mnt/isolinux/isolinux.cfg:  append initrd=/3.img inst.ks=http://127.0.0.1:80/cblr/svc/op/autoinstall/profile/cs9test-x86_64 inst.repo=http://127.0.0.1/cblr/links/cs9test-x86_64
/mnt/isolinux/isolinux.cfg:  APPEND initrd=/1.img inst.ks=http://127.0.0.1:80/cblr/svc/op/autoinstall/system/rawhide inst.repo=http://download.fedoraproject.org/pub/fedora/linux/releases/38/Everything/x86_64/os/
/mnt/isolinux/isolinux.cfg:  APPEND initrd=/1.img inst.ks=http://127.0.0.1:80/cblr/svc/op/autoinstall/system/test inst.repo=http://download.fedoraproject.org/pub/fedora/linux/releases/38/Everything/x86_64/os/
```
