### ISSUE TITLE
Buildiso systems should add network configuration to the append line

### ISSUE THREAD

**Issue by jimi-c** [cobbler/cobbler#414]
When using buildiso to build systems, any systems that have a static management interface defined should add the ip/netmask/gateway options to the append_line for use in the isolinux.cfg.

**Comment by r08ertliu** [comment]
This feature(commit [0c6f177](https://github.com/cobbler/cobbler/commit/0c6f177cbdd90f8222514e4c212293d14b522673)) may conflict to [arbitrary NIC naming](http://cobbler.github.io/manuals/2.8.0/4/1_-_Advanced_Networking.html), since cobbler allow setting system interface name as user wanted.
For example, assume we have two NIC on a system
NIC1:
MAC: 00:11:22:AA:BB:CC
Name: ens160

NIC2:
MAC: 00:11:22:AA:BB:DD
Name: ens192

Cobbler:
`cobbler system edit --name mysys01 --interface mgmt --mac=00:11:22:AA:BB:CC --management true`
`cobbler system edit --name mysys01 --interface private --mac=00:11:22:AA:BB:DD --management false`

For installing Ubuntu 16.04, this feature appends "netcfg/choose_interface=**mgmt**" to kernel option in pxelinux.cfg instead of "netcfg/choose_interface=**ens160**". This cause netcfg cannot found interface **mgmt** and break installation into failure.

Instead, we can append `interface=00:11:22:AA:BB:CC` to kernel option. Kernel will find this MAC belong to ens160 and activate DHCP on it. Further using preseed early command to query name/MAC mapping and check management flag to generate network debconf like `d-i netcfg/choose_interface string ens160`. Then use debconf-set-selections to insert it.

[Arbitrary NIC naming](http://cobbler.github.io/manuals/2.8.0/4/1_-_Advanced_Networking.html) is nice for current using consistent network device naming. Since it take effort to know the actual name of the NIC in system. Using MAC to identify NIC and get actual interface name would much friendly.
