### ISSUE TITLE
Support mirroring of pulp repositories

### ISSUE THREAD

**Issue by robinbowes** [cobbler/cobbler#692]
When working with a secured katello (pulp) repo, yum (and therefore repomirror) needs to use custom ssl options to authorise connection:
'''
sslverify = 1
sslcacert = /etc/rhsm/ca/candlepin-local.pem
sslclientkey = /etc/pki/entitlement/7460915689764365934-key.pem
sslclientcert = /etc/pki/entitlement/7460915689764365934.pem
'''
I can add these to the cobbler repo config with the --yumopts switch. However, these custom opts are not written to the temp repo file used by repomirror. Indeed, the options used to connect to the mirror source are different to the ones that any client would use to connect to the mirrored repo on cobbler.

I've worked around the issue for now by hacking action_reposync.py to write the custom yumopts to the temp repo file used for mirroring.

However, the reposync then fails because it is not able to retrieve repomd.xml using wget, presumably because the repo is secured with SSL client certs.

Is there any love for supported mirroring from ssl-secured repos, eg. katello (pulp)

**Comment by teridon** [comment]
This support is also required to support RedHat repositories using RHSM.  RHN support is going away in July 2017, so this support must be added to cobbler for it to continue to be able to support Redhat systems.  The "Hacky attempt" code seems to allow cobbler to download packages, but not the repomd.xml files.  Since then, action_reposync.py has changed to using urlgrabber.  urlgrabber has support for SSL client cert authentication, but I don't know how to patch action_reposync.py so that it passes the yum options using the proper urlgrabber arguments.   Here's a kludgy way to do it, but it breaks yum repos that do not have these arguments defined:

-            urlgrabber.grabber.urlgrab(src, filename=dst, proxies=proxies)
+            urlgrabber.grabber.urlgrab(src, filename=dst, proxies=proxies, ssl_cert=repo.yumopts['sslclientcert'], ssl_key=repo.yumopts['sslclientkey'], ssl_verify_peer=False)

**Comment by teridon** [comment]
see https://github.com/cobbler/cobbler/pull/1763

**Comment by SchoolGuy** [comment]
This was fixed by #1763
